#!/bin/bash

# Dieses Skript sendet eine Liste von Themen an den Endpunkt http://localhost:8080/themen.
# Für jedes Thema wird eine separate POST-Anfrage mit dem Text 'Fakten über <Thema>' gesendet.

# Array mit allen zu erstellenden Themen
themen=(
  "Schweißfüße"
  "Lichtgeschwindigkeit"
  "Sonnensystem"
  "Raketen"
  "Raumfahrt"
  "Mars"
  "Hunde"
  "Igel"
  "Katzen"
  "Vögel"
  "Fische"
  "Insekten"
  "Spinnen"
  "Reptilien"
  "Amphibien"
  "Säugetiere"
  "Pflanzen"
  "Bäume"
  "Blumen"
  "Pilze"
  "Algen"
  "Bakterien"
  "Viren"
  "DNA"
  "RNA"
  "Proteine"
  "Zellen"
  "Organe"
  "Gehirn"
  "Herz"
  "Lunge"
  "Leber"
  "Niere"
  "Magen"
  "Darm"
  "Blut"
  "Knochen"
  "Muskeln"
  "Nerven"
  "Haut"
  "Haare"
  "Nägel"
  "Augen"
  "Ohren"
  "Nase"
  "Zunge"
  "Sinne"
  "Schlaf"
  "Träume"
  "Erinnerung"
  "Emotionen"
  "Glück"
  "Trauer"
  "Angst"
  "Wut"
  "Liebe"
  "Hass"
  "Freundschaft"
  "Familie"
  "Sprache"
  "Schrift"
  "Lesen"
  "Schreiben"
  "Mathematik"
  "Physik"
  "Chemie"
  "Biologie"
  "Astronomie"
  "Geologie"
  "Meteorologie"
  "Ozeanographie"
  "Ökologie"
  "Umwelt"
  "Klima"
  "Klimawandel"
  "Erde"
  "Mond"
  "Sonne"
  "Sterne"
  "Galaxien"
  "Universum"
  "Schwarze Löcher"
  "Exoplaneten"
  "Kometen"
  "Asteroiden"
  "Meteoriten"
  "Supernova"
  "Quantenphysik"
  "Relativitätstheorie"
  "Gravitation"
  "Licht"
  "Schall"
  "Wärme"
  "Elektrizität"
  "Magnetismus"
  "Atom"
  "Molekül"
  "Elemente"
  "Periodensystem"
  "Säure"
  "Base"
  "Salz"
  "Wasser"
  "Luft"
  "Feuer"
  "Vulkane"
  "Erdbeben"
  "Tsunamis"
  "Stürme"
  "Tornados"
  "Hurrikane"
  "Blitze"
  "Regen"
  "Schnee"
  "Eis"
  "Gletscher"
  "Wüsten"
  "Regenwälder"
  "Korallenriffe"
  "Ozeane"
  "Meere"
  "Seen"
  "Flüsse"
  "Berge"
  "Täler"
  "Höhlen"
  "Inseln"
  "Kontinente"
  "Polarkreise"
  "Äquator"
  "Zeitzonen"
  "Karten"
  "Globen"
  "GPS"
  "Satelliten"
  "Teleskope"
  "Mikroskope"
  "Computer"
  "Internet"
  "Handys"
  "Smartphones"
  "Tablets"
  "Laptops"
  "Software"
  "Hardware"
  "Programmierung"
  "Künstliche Intelligenz (KI)"
  "Robotik"
  "Nanotechnologie"
  "Biotechnologie"
  "Genetische Modifikation"
  "Klonen"
  "Virtuelle Realität (VR)"
  "Augmented Reality (AR)"
  "Blockchain"
  "Kryptowährungen"
  "Big Data"
  "Cybersicherheit"
  "Erneuerbare Energien"
  "Solarzellen"
  "Windkraft"
  "Wasserkraft"
  "Geothermie"
  "Kernenergie"
  "Fossile Brennstoffe"
  "Öl"
  "Gas"
  "Kohle"
  "Plastik"
  "Recycling"
  "Müll"
  "Verschmutzung"
  "Ozonloch"
  "Saurer Regen"
  "Artensterben"
  "Naturschutz"
  "Umweltschutz"
  "Vegetarismus"
  "Veganismus"
  "Ernährung"
  "Vitamine"
  "Mineralien"
  "Kohlenhydrate"
  "Proteine"
  "Fette"
  "Kaffee"
  "Tee"
  "Schokolade"
  "Zucker"
  "Brot"
  "Käse"
  "Milch"
  "Eier"
  "Fleisch"
  "Gemüse"
  "Obst"
  "Getreide"
  "Reis"
  "Nudeln"
  "Kartoffeln"
  "Bier"
  "Wein"
  "Spirituosen"
  "Rauchen"
  "Alkohol"
  "Drogen"
  "Medikamente"
  "Krankheiten"
  "Impfungen"
  "Antibiotika"
  "Operationen"
  "Ärzte"
  "Krankenhäuser"
  "Therapien"
  "Psychologie"
  "Psychiatrie"
  "Depressionen"
  "Angststörungen"
  "Burnout"
  "Stress"
  "Meditation"
  "Yoga"
  "Sport"
  "Fitness"
  "Olympische Spiele"
  "Fußball"
  "Basketball"
  "Tennis"
  "Schwimmen"
  "Laufen"
  "Radfahren"
  "Wandern"
  "Klettern"
  "Skifahren"
  "Snowboarden"
  "Segeln"
  "Surfen"
  "Tauchen"
  "Fliegen"
  "Autos"
  "Fahrräder"
  "Züge"
  "Flugzeuge"
  "Schiffe"
  "U-Boote"
  "Busse"
  "Taxis"
  "U-Bahnen"
  "Straßenbahnen"
  "Roller"
  "Skateboards"
  "Schuhe"
  "Kleidung"
  "Mode"
  "Schmuck"
  "Uhren"
  "Häuser"
  "Wohnungen"
  "Gebäude"
  "Architektur"
  "Städte"
  "Dörfer"
  "Länder"
  "Grenzen"
  "Staaten"
  "Regierungen"
  "Demokratie"
  "Diktatur"
  "Monarchie"
  "Republik"
  "Politik"
  "Wirtschaft"
  "Handel"
  "Geld"
  "Banken"
  "Aktien"
  "Börse"
  "Steuern"
  "Inflation"
  "Deflation"
  "Arbeitslosigkeit"
  "Globalisierung"
  "Entwicklungsländer"
  "Industrieländer"
  "Kriege"
  "Frieden"
  "Diplomatie"
  "Vereinte Nationen"
  "Europäische Union"
  "NATO"
  "Geschichte"
  "Prähistorie"
  "Antike"
  "Mittelalter"
  "Neuzeit"
  "Industrielle Revolution"
  "Weltkriege"
  "Kalter Krieg"
  "Berliner Mauer"
  "Römisches Reich"
  "Ägypten"
  "Griechenland"
  "China"
  "Indien"
  "Japan"
  "Amerika"
  "Afrika"
  "Australien"
  "Europäische Geschichte"
  "Asiatische Geschichte"
  "Amerikanische Geschichte"
  "Afrikanische Geschichte"
  "Ozeanische Geschichte"
  "Philosophie"
  "Religion"
  "Christentum"
  "Islam"
  "Judentum"
  "Buddhismus"
  "Hinduismus"
  "Atheismus"
  "Agnostizismus"
  "Mythologie"
  "Legenden"
  "Märchen"
  "Fabeln"
  "Literatur"
  "Romane"
  "Gedichte"
  "Theaterstücke"
  "Dramen"
  "Komödien"
  "Tragödien"
  "Filme"
  "Serien"
  "Dokumentationen"
  "Musik"
  "Klassik"
  "Jazz"
  "Rock"
  "Pop"
  "Hip-Hop"
  "Elektronische Musik"
  "Volksmusik"
  "Tanz"
  "Ballett"
  "Modern Dance"
  "Salsa"
  "Tango"
  "Kunst"
  "Malerei"
  "Skulptur"
  "Fotografie"
  "Design"
  "Keramik"
  "Glas"
  "Textilien"
  "Holz"
  "Metall"
  "Stein"
  "Papier"
  "Pappe"
  "Druck"
  "Buchdruck"
  "Zeitungen"
  "Zeitschriften"
  "Bücher"
  "Comics"
  "Mangas"
  "Videospiele"
  "Brettspiele"
  "Kartenspiele"
  "Rätsel"
  "Illusionen"
  "Zauberei"
  "Magie"
  "Aberglaube"
  "Glücksbringer"
  "Unglück"
  "Schicksal"
  "Freiheit"
  "Gerechtigkeit"
  "Ethik"
  "Moral"
  "Werte"
  "Normen"
  "Traditionen"
  "Bräuche"
  "Feiertage"
  "Rituale"
  "Flaggen"
  "Hymnen"
  "Wappen"
  "Münzen"
  "Briefmarken"
  "Sammlungen"
  "Hobbys"
  "Freizeit"
  "Reisen"
  "Urlaub"
  "Abenteuer"
  "Entdeckungen"
  "Erfindungen"
  "Innovationen"
  "Forschung"
  "Wissenschaftler"
  "Erfinder"
  "Pioniere"
  "Nobelpreise"
  "Rekorde"
  "Statistiken"
  "Zahlen"
  "Daten"
  "Algorithmen"
  "Logik"
  "Mathematische Operationen"
  "Geometrie"
  "Algebra"
  "Infinitesimalrechnung"
  "Statistik"
  "Wahrscheinlichkeit"
  "Muster"
  "Symmetrie"
  "Fraktale"
  "Dimensionen"
  "Null"
  "Unendlich"
  "Primzahlen"
  "Pi"
  "Eulersche Zahl"
  "Goldener Schnitt"
  "Fibonacci-Folge"
  "Logarithmus"
  "Vektoren"
  "Matrizen"
  "Graphen"
  "Netzwerke"
  "Topologie"
  "Chaostheorie"
  "Kybernetik"
  "Roboter"
  "Automatisierung"
  "Sensoren"
  "Aktuatoren"
  "Mikrocontroller"
  "Schaltkreise"
  "Transistoren"
  "Dioden"
  "Widerstände"
  "Kondensatoren"
  "Induktivitäten"
  "Chips"
  "Prozessoren"
  "Speicher"
  "Festplatten"
  "SSDs"
  "USB-Sticks"
  "CDs"
  "DVDs"
  "Blu-rays"
  "Disketten"
  "Lochkarten"
  "Rechenschieber"
  "Abakus"
  "Uhrwerk"
  "Getriebe"
  "Hebel"
  "Räder"
  "Achsen"
  "Motoren"
  "Generatoren"
  "Turbinen"
  "Pumpen"
  "Ventile"
  "Rohre"
  "Kabel"
  "Drähte"
  "Lötstellen"
  "Schrauben"
  "Muttern"
  "Nägel"
  "Hammer"
  "Sägen"
  "Bohrmaschinen"
  "Zangen"
  "Schraubendreher"
  "Maßbänder"
  "Wasserwaagen"
  "Lineale"
  "Zirkel"
  "Geodreiecke"
  "Stifte"
  "Bleistifte"
  "Kugelschreiber"
  "Füller"
  "Radiergummis"
  "Spitzer"
  "Umschläge"
  "Briefe"
  "Pakete"
  "Postämter"
  "Postkarten"
  "Telefon"
  "Fax"
  "Radio"
  "Fernsehen"
  "Kameras"
  "Mikrofone"
  "Lautsprecher"
  "Kopfhörer"
  "Verstärker"
  "Mischpulte"
  "Instrumente"
  "Gitarren"
  "Klaviere"
  "Schlagzeuge"
  "Geigen"
  "Flöten"
  "Trompeten"
  "Saxophone"
  "Harfen"
  "Oboen"
  "Klarinetten"
  "Posaunen"
  "Tuben"
  "Akkordeons"
  "Orgeln"
  "Cembalo"
  "Sitar"
  "Didgeridoo"
  "Djembe"
  "Maracas"
  "Tamburin"
  "Xylophon"
  "Glockenspiel"
  "Metallophone"
  "Vibraphon"
  "Congas"
  "Bongos"
  "Cajon"
  "Mundharmonika"
  "Blockflöte"
  "Piccolo"
  "Fagott"
  "Kontrabass"
  "Cello"
  "Viola"
  "Mandoline"
  "Ukulele"
  "Banjo"
  "Laute"
  "Zither"
  "Dulcimer"
  "Hackbrett"
  "Schalmei"
  "Dudelsack"
  "Keltische Harfe"
  "Panflöte"
  "Okarina"
  "Theremin"
  "Synthesizer"
  "Drumcomputer"
  "Sampler"
  "Plattenspieler"
  "Kassettenrekorder"
  "CD-Player"
  "MP3-Player"
  "Podcasts"
  "Hörbücher"
  "E-Books"
  "Graphic Novels"
  "Kurzgeschichten"
  "Lyrik"
  "Essays"
  "Biographien"
  "Autobiographien"
  "Sachbücher"
  "Lexika"
  "Wörterbücher"
  "Atlanten"
  "Kochbücher"
  "Reiseführer"
  "Geschichtsbücher"
  "Wissenschaftliche Artikel"
  "Forschungsberichte"
  "Patente"
  "Normen"
  "Gesetze"
  "Verordnungen"
  "Verträge"
  "Abkommen"
  "Reden"
  "Predigten"
  "Liedertexte"
  "Drehbücher"
  "Bühnenbilder"
  "Kostüme"
  "Maske"
  "Beleuchtung"
  "Ton"
  "Regie"
  "Schauspieler"
  "Tänzer"
  "Musiker"
  "Dirigenten"
  "Chöre"
  "Orchester"
  "Bands"
  "Solisten"
  "Komponisten"
  "Texter"
  "Regisseure"
  "Produzenten"
  "Kameraleute"
  "Editoren"
  "Cutter"
  "Visuelle Effekte (VFX)"
  "Animation"
  "Stop-Motion"
  "CGI"
  "Zeichentrick"
  "Cartoons"
  "Figuren"
  "Charaktere"
  "Storytelling"
  "Handlung"
  "Plot"
  "Setting"
  "Genre"
  "Kino"
  "Streamingdienste"
  "Theater"
  "Oper"
  "Konzerte"
  "Festivals"
  "Museen"
  "Galerien"
  "Ausstellungen"
  "Denkmäler"
  "Wahrzeichen"
  "Pyramiden"
  "Eiffelturm"
  "Freiheitsstatue"
  "Kolosseum"
  "Chinesische Mauer"
  "Taj Mahal"
  "Akropolis"
  "Machu Picchu"
  "Stonehenge"
  "Christus der Erlöser"
  "Burj Khalifa"
  "Golden Gate Bridge"
  "Sydney Opera House"
  "Big Ben"
  "Rotes Quadrat"
  "Vatikanstadt"
  "Kreml"
  "Brandburger Tor"
  "Kölner Dom"
  "Neuschwanstein"
  "Mount Everest"
  "Grand Canyon"
  "Niagarafälle"
  "Amazonas"
  "Nil"
  "Sahara"
  "Antarktis"
  "Arktis"
  "Nordpol"
  "Südpol"
  "Vulkan Ätna"
  "Mount Fuji"
  "Victoriafälle"
  "Great Barrier Reef"
  "Totes Meer"
  "Bodensee"
  "Alpen"
  "Anden"
  "Rocky Mountains"
  "Himalaya"
  "Schwäbische Alb"
  "Schwarzwald"
  "Bayrischer Wald"
  "Harz"
  "Eifel"
  "Mosel"
  "Rhein"
  "Donau"
  "Elbe"
  "Spree"
  "Isar"
  "Neckar"
  "Main"
  "Weser"
  "Oder"
  "Rügen"
  "Sylt"
  "Borkum"
  "Norderney"
  "Helgoland"
  "Fehmarn"
  "Usedom"
  "Mallorca"
  "Kreta"
  "Sardinien"
  "Sizilien"
  "Hawaii"
  "Malediven"
  "Fidschi"
  "Karibik"
  "Island"
  "Grönland"
  "Patagonien"
  "Sibirien"
  "Mongolei"
  "Tibet"
  "Everest"
  "K2"
  "Mont Blanc"
  "Kilimandscharo"
  "Zugspitze"
  "Matterhorn"
  "Faszination"
  "Geheimnis"
  "Epos"
  "Saga"
  "Folklore"
  "Brauchtum"
  "Tradition"
  "Ritus"
  "Zeremonie"
  "Glaube"
  "Spiritualität"
  "Gebet"
  "Karma"
  "Reinkarnation"
  "Jenseits"
  "Paradies"
  "Hölle"
  "Engel"
  "Dämonen"
  "Geister"
  "Vampire"
  "Werwölfe"
  "Zombies"
  "Einhörner"
  "Drachen"
  "Meerjungfrauen"
  "Kobolde"
  "Elfen"
  "Feen"
  "Trolle"
  "Riesen"
  "Zwerge"
  "Götter"
  "Göttinnen"
  "Heilige"
  "Propheten"
  "Weise"
  "Philosophen"
  "Denker"
  "Wissenschaftler"
  "Künstler"
  "Musiker"
  "Dichter"
  "Schriftsteller"
  "Maler"
  "Bildhauer"
  "Architekten"
  "Designer"
  "Modeschöpfer"
  "Fotografen"
  "Schauspieler"
  "Regisseure"
  "Sänger"
  "Tänzer"
  "Komponisten"
  "Dirigenten"
  "Autoren"
  "Journalisten"
  "Reporter"
  "Moderatoren"
  "Blogger"
  "Vlogger"
  "Influencer"
  "Unternehmer"
  "Manager"
  "Arbeiter"
  "Handwerker"
  "Bauern"
  "Fischer"
  "Jäger"
  "Sammler"
  "Nomaden"
  "Siedler"
  "Entdecker"
  "Abenteurer"
  "Pioniere"
  "Astronauten"
  "Kosmonauten"
  "Forschungstaucher"
  "Bergsteiger"
  "Extremsportler"
  "Soldaten"
  "Polizisten"
  "Feuerwehrleute"
  "Ärzte"
  "Krankenpfleger"
  "Lehrer"
  "Professoren"
  "Studenten"
  "Schüler"
  "Jugendliche"
  "Erwachsene"
  "Senioren"
  "Eltern"
  "Geschwister"
  "Großeltern"
  "Tanten"
  "Onkel"
  "Neffen"
  "Nichten"
  "Cousins"
  "Cousinen"
  "Ehepartner"
  "Freunde"
  "Kollegen"
  "Nachbarn"
  "Gemeinschaft"
  "Gesellschaft"
  "Kultur"
  "Zivilisation"
  "Nation"
  "Staat"
  "Stadt"
  "Dorf"
  "Metropole"
  "Megastadt"
  "Slum"
  "Vorstadt"
  "Landwirtschaft"
  "Industrie"
  "Dienstleistung"
  "Finanzen"
  "Bankwesen"
  "Versicherungen"
  "Immobilien"
  "Tourismus"
  "Verkehr"
  "Logistik"
  "Kommunikation"
  "Medien"
  "Bildung"
  "Gesundheit"
  "Soziales"
  "Sicherheit"
  "Justiz"
  "Militär"
  "Katastrophenschutz"
  "Freiwilligenarbeit"
  "Wohltätigkeit"
  "Spenden"
  "Hilfsorganisationen"
  "Friedensbewegung"
  "Bürgerrechte"
  "Menschenrechte"
  "Gleichheit"
  "Toleranz"
  "Respekt"
  "Integration"
  "Migration"
  "Flüchtlinge"
  "Armut"
  "Reichtum"
  "Ungleichheit"
  "Soziale Gerechtigkeit"
  "Kriminalität"
  "Verbrechen"
  "Strafe"
  "Recht"
  "Gesetz"
  "Verfassung"
  "Gerichte"
  "Anwälte"
  "Richter"
  "Jury"
  "Gefängnisse"
  "Todesstrafe"
  "Folter"
  "Kriegsverbrechen"
  "Völkermord"
  "Terrorismus"
  "Revolution"
  "Protest"
  "Streik"
  "Demonstration"
  "Wahlen"
  "Abstimmungen"
  "Parteien"
  "Regierung"
  "Opposition"
  "Präsident"
  "Kanzler"
  "Premierminister"
  "König"
  "Kaiser"
  "Diktator"
  "Papst"
  "Geistliche"
  "Priester"
  "Rabbis"
  "Imame"
  "Mönche"
  "Nonnen"
  "Heilige Bücher"
  "Tempel"
  "Kirchen"
  "Moscheen"
  "Synagogen"
  "Pagoden"
  "Altäre"
  "Schreine"
  "Reliquien"
  "Pilgerfahrten"
  "Sakramente"
  "Feste"
  "Fasten"
  "Gebete"
  "Lieder"
  "Tänze"
  "Mythen"
  "Sagen"
  "Epen"
  "Prophezeiungen"
  "Orakel"
  "Horoskope"
  "Astrologie"
  "Alchemie"
  "Hexen"
  "Zyklopen"
  "Sphinxe"
  "Greife"
  "Phönixe"
  "Chimären"
  "Leprechauns"
  "Banshees"
  "Einhorn"
  "Greif"
  "Phönix"
  "Chimäre"
  "Werwolf (Mythologie)"
  "Vampir (Mythologie)"
  "Zombie (Mythologie)"
  "Drache (Mythologie)"
  "Kraken (Mythologie)"
  "Yeti (Kryptozoologie)"
  "Bigfoot (Kryptozoologie)"
  "Loch Ness Monster (Kryptozoologie)"
  "Chupacabra (Kryptozoologie)"
  "Mothman (Kryptozoologie)"
  "Jersey Devil (Kryptozoologie)"
  "Wendigo (Mythologie)"
  "Skinwalker (Mythologie)"
  "Kitsune (Japanische Mythologie)"
  "Tanuki (Japanische Mythologie)"
  "Kappa (Japanische Mythologie)"
  "Oni (Japanische Mythologie)"
  "Yokai (Japanische Mythologie)"
  "Tengu (Japanische Mythologie)"
  "Raijin (Japanische Mythologie)"
  "Fujin (Japanische Mythologie)"
  "Amaterasu (Japanische Mythologie)"
  "Susanoo (Japanische Mythologie)"
  "Tsukuyomi (Japanische Mythologie)"
  "Hades (Griechische Mythologie)"
  "Zeus (Griechische Mythologie)"
  "Hera (Griechische Mythologie)"
  "Poseidon (Griechische Mythologie)"
  "Demeter (Griechische Mythologie)"
  "Athene (Griechische Mythologie)"
  "Apollon (Griechische Mythologie)"
  "Artemis (Griechische Mythologie)"
  "Ares (Griechische Mythologie)"
  "Aphrodite (Griechische Mythologie)"
  "Hephaistos (Griechische Mythologie)"
  "Hermes (Griechische Mythologie)"
  "Dionysos (Griechische Mythologie)"
  "Eros (Griechische Mythologie)"
  "Nike (Griechische Mythologie)"
  "Pan (Griechische Mythologie)"
  "Asklepios (Griechische Mythologie)"
  "Morientes (Griechische Mythologie)"
  "Thanatos (Griechische Mythologie)"
  "Hypnos (Griechische Mythologie)"
  "Erebos (Griechische Mythologie)"
  "Nyx (Griechische Mythologie)"
  "Gaia (Griechische Mythologie)"
  "Uranos (Griechische Mythologie)"
  "Kronos (Griechische Mythologie)"
  "Rhea (Griechische Mythologie)"
  "Okeanos (Griechische Mythologie)"
  "Tethys (Griechische Mythologie)"
  "Hyperion (Griechische Mythologie)"
  "Theia (Griechische Mythologie)"
  "Koios (Griechische Mythologie)"
  "Phoebe (Griechische Mythologie)"
  "Iapetos (Griechische Mythologie)"
  "Klymene (Griechische Mythologie)"
  "Mnemosyne (Griechische Mythologie)"
  "Themis (Griechische Mythologie)"
  "Epimetheus (Griechische Mythologie)"
  "Atlas (Griechische Mythologie)"
  "Medea (Griechische Mythologie)"
  "Jason (Griechische Mythologie)"
  "Argonauten (Griechische Mythologie)"
  "Achilles (Griechische Mythologie)"
  "Hektor (Griechische Mythologie)"
  "Odysseus (Griechische Mythologie)"
  "Helena (Griechische Mythologie)"
  "Paris (Griechische Mythologie)"
  "Troja (Griechische Mythologie)"
  "Trojanisches Pferd (Griechische Mythologie)"
  "Amazonen (Griechische Mythologie)"
  "Siren (Griechische Mythologie)"
  "Cerberus (Griechische Mythologie)"
  "Hydra (Griechische Mythologie)"
  "Chimaera (Griechische Mythologie)"
  "Nemeischer Löwe (Griechische Mythologie)"
  "Erymanthischer Eber (Griechische Mythologie)"
  "Stymphalische Vögel (Griechische Mythologie)"
  "Delphi (Griechische Mythologie)"
  "Olymp (Griechische Mythologie)"
  "Underworld (Griechische Mythologie)"
  "Tartarus (Griechische Mythologie)"
  "Elysium (Griechische Mythologie)"
  "Fluss Styx (Griechische Mythologie)"
  "Charon (Griechische Mythologie)"
  "Orpheus (Griechische Mythologie)"
  "Eurydike (Griechische Mythologie)"
  "Dädalus (Griechische Mythologie)"
  "Ikarus (Griechische Mythologie)"
  "Theseus (Griechische Mythologie)"
  "Ariadne (Griechische Mythologie)"
  "Minos (Griechische Mythologie)"
  "König Midas (Griechische Mythologie)"
  "Sisyphos (Griechische Mythologie)"
  "Tantalus (Griechische Mythologie)"
  "Pandora (Griechische Mythologie)"
  "Herakles (Griechische Mythologie)"
  "Thron (Herrschaft)"
  "Krone (Symbol)"
  "Zepter (Symbol)"
  "Reichsapfel (Symbol)"
  "Schwert (Symbol)"
  "Schild (Symbol)"
  "Rüstung (Militär)"
  "Pferd (Tier)"
  "Kutsche (Verkehr)"
  "Schiff (Transport)"
  "Festung (Architektur)"
  "Burg (Architektur)"
  "Palast (Architektur)"
  "Kathedrale (Architektur)"
  "Obelisk (Architektur)"
  "Hieroglyphen (Schrift)"
  "Keilschrift (Schrift)"
  "Runen (Schrift)"
  "Papyrus (Material)"
  "Pergament (Material)"
  "Tontafel (Schrift)"
  "Buchrolle (Medium)"
  "Manuskript (Schriftstück)"
  "Inkunabel (Buch)"
  "Handschrift (Schrift)"
  "Druckpresse (Erfindung)"
  "Gutenberg (Person)"
  "Luther (Person)"
  "Reformation (Geschichte)"
  "Gegenreformation (Geschichte)"
  "Dreißigjähriger Krieg (Geschichte)"
  "Westfälischer Friede (Geschichte)"
  "Französische Revolution (Geschichte)"
  "Napoleon (Person)"
  "Waterloo (Schlacht)"
  "Dampfmaschine (Erfindung)"
  "Eisenbahn (Verkehrsmittel)"
  "Fabriken (Gebäude)"
  "Urbanisierung (Prozess)"
  "Proletariat (Soziale Klasse)"
  "Bourgeoisie (Soziale Klasse)"
  "Sozialismus (Ideologie)"
  "Kommunismus (Ideologie)"
  "Kapitalismus (Wirtschaftssystem)"
  "Feudalismus (Wirtschaftssystem)"
  "Absolutismus (Herrschaftsform)"
  "Aufklärung (Epoche)"
  "Romantik (Epoche)"
  "Biedermeier (Epoche)"
  "Vormärz (Epoche)"
  "1848er Revolution (Geschichte)"
  "Deutsches Kaiserreich (Geschichte)"
  "Weimarer Republik (Geschichte)"
  "Nationalsozialismus (Ideologie)"
  "Zweiter Weltkrieg (Geschichte)"
  "Holocaust (Geschichte)"
  "Wiedervereinigung (Geschichte)"
  "Covid-19 (Virus)"
  "Impfstoff (Medizin)"
  "Quarantäne (Maßnahme)"
  "Lockdown (Maßnahme)"
  "Homeoffice (Arbeitsform)"
  "Online-Bildung (Lehre)"
  "Soziale Medien (Technologie)"
  "Fake News (Information)"
  "Cybermobbing (Internetphänomen)"
  "Datenschutz (Recht)"
  "Überwachung (Kontrolle)"
  "Privatsphäre (Recht)"
  "Sicherheit (Zustand)"
  "Extremismus (Ideologie)"
  "Radikalisierung (Prozess)"
  "Hassrede (Kommunikation)"
  "Zensur (Kontrolle)"
  "Meinungsfreiheit (Recht)"
  "Pressefreiheit (Recht)"
  "Autokratie (Staatsform)"
  "Theokratie (Staatsform)"
  "Anarchie (Zustand)"
  "Föderalismus (Staatsform)"
  "Zentralismus (Staatsform)"
  "Gesetzgebung (Prozess)"
  "Rechtsprechung (Prozess)"
  "Exekutive (Regierung)"
  "Legislative (Parlament)"
  "Judikative (Gerichte)"
  "Bürgerinitiative (Politik)"
  "Petition (Politik)"
  "Volksbegehren (Politik)"
  "Volksentscheid (Politik)"
  "Referendum (Politik)"
  "Lobbyismus (Politik)"
  "Korruption (Kriminalität)"
  "Transparenz (Politik)"
  "Good Governance (Politik)"
  "Nachhaltigkeit (Umwelt)"
  "Kreislaufwirtschaft (Wirtschaft)"
  "Grüne Energie (Energie)"
  "Klimaneutralität (Umwelt)"
  "CO2-Fußabdruck (Umwelt)"
  "Emissionen (Umwelt)"
  "Treibhauseffekt (Klima)"
  "Globale Erwärmung (Klima)"
  "Meeresspiegelanstieg (Klima)"
  "Biodiversität (Biologie)"
  "Ökosystem (Biologie)"
  "Nahrungskette (Biologie)"
  "Symbiose (Biologie)"
  "Parasitismus (Biologie)"
  "Mutation (Biologie)"
  "Selektion (Biologie)"
  "Anpassung (Biologie)"
  "Evolution (Biologie)"
  "Genetik (Biologie)"
  "Chromosomen (Biologie)"
  "DNA-Sequenzierung (Biologie)"
  "Gentechnik (Biologie)"
  "Stammzellen (Biologie)"
  "Organismus (Biologie)"
  "Mikroorganismen (Biologie)"
  "Tiere (Biologie)"
  "Mensch (Biologie)"
  "Körper (Anatomie)"
  "Blutkreislauf (Anatomie)"
  "Verdauungssystem (Anatomie)"
  "Immunsystem (Anatomie)"
  "Hormone (Biochemie)"
  "Enzyme (Biochemie)"
  "Mineralstoffe (Biochemie)"
  "Stoffwechsel (Biologie)"
  "Atmung (Biologie)"
  "Fortpflanzung (Biologie)"
  "Geburt (Biologie)"
  "Alterung (Biologie)"
  "Tod (Biologie)"
  "Gesundheit (Medizin)"
  "Chirurgie (Medizin)"
  "Pharmakologie (Medizin)"
  "Diagnose (Medizin)"
  "Prävention (Medizin)"
  "Impfung (Medizin)"
  "Pilzinfektion (Medizin)"
  "Parasiten (Medizin)"
  "Krebs (Krankheit)"
  "Diabetes (Krankheit)"
  "Herzinfarkt (Krankheit)"
  "Schlaganfall (Krankheit)"
  "Autoimmunerkrankungen (Krankheit)"
  "Psychische Erkrankungen (Krankheit)"
  "Depression (Krankheit)"
  "Angststörung (Krankheit)"
  "Schizophrenie (Krankheit)"
  "Bipolare Störung (Krankheit)"
  "Essstörung (Krankheit)"
  "Sucht (Krankheit)"
  "Psychotherapie (Psychologie)"
  "Kognitive Verhaltenstherapie (Psychologie)"
  "Psychoanalyse (Psychologie)"
  "Gruppentherapie (Psychologie)"
  "Medikamentöse Therapie (Medizin)"
  "Trauma (Psychologie)"
  "Posttraumatische Belastungsstörung (Psychologie)"
  "Resilienz (Psychologie)"
  "Coping (Psychologie)"
  "Mitgefühl (Psychologie)"
  "Zufriedenheit (Emotion)"
  "Freude (Emotion)"
  "Hoffnung (Emotion)"
  "Optimismus (Haltung)"
  "Pessimismus (Haltung)"
  "Eifersucht (Emotion)"
  "Neid (Emotion)"
  "Scham (Emotion)"
  "Schuld (Emotion)"
  "Reue (Emotion)"
  "Vergebung (Handlung)"
  "Dankbarkeit (Emotion)"
  "Langeweile (Emotion)"
  "Einsamkeit (Zustand)"
  "Mut (Eigenschaft)"
  "Tapferkeit (Eigenschaft)"
  "Feigheit (Eigenschaft)"
  "Ehrlichkeit (Eigenschaft)"
  "Lüge (Handlung)"
  "Vertrauen (Zustand)"
  "Misstrauen (Zustand)"
  "Loyalität (Eigenschaft)"
  "Verrat (Handlung)"
  "Geduld (Eigenschaft)"
  "Ungeduld (Eigenschaft)"
  "Disziplin (Eigenschaft)"
  "Selbstbeherrschung (Eigenschaft)"
  "Willenskraft (Eigenschaft)"
  "Konzentration (Psychologie)"
  "Aufmerksamkeit (Psychologie)"
  "Lernen (Psychologie)"
  "Gedächtnis (Psychologie)"
  "Intelligenz (Psychologie)"
  "Problemlösung (Psychologie)"
  "Entscheidungsfindung (Psychologie)"
  "Dialekt (Linguistik)"
  "Akzent (Linguistik)"
  "Grammatik (Linguistik)"
  "Wortschatz (Linguistik)"
  "Satzbau (Linguistik)"
  "Rhetorik (Sprache)"
  "Debatte (Kommunikation)"
  "Verhandlung (Kommunikation)"
  "Argumentation (Logik)"
  "Fehlschluss (Logik)"
  "Kritisches Denken (Philosophie)"
  "Argument (Philosophie)"
  "Prämisse (Logik)"
  "Konklusion (Logik)"
  "Gültigkeit (Logik)"
  "Schlüssigkeit (Logik)"
  "Wahrheit (Philosophie)"
  "Erkenntnis (Philosophie)"
  "Wissen (Philosophie)"
  "Skeptizismus (Philosophie)"
  "Rationalismus (Philosophie)"
  "Empirismus (Philosophie)"
  "Idealismus (Philosophie)"
  "Materialismus (Philosophie)"
  "Existenzialismus (Philosophie)"
  "Humanismus (Philosophie)"
  "Feminismus (Philosophie)"
  "Liberalismus (Philosophie)"
  "Konservatismus (Philosophie)"
  "Anarchismus (Philosophie)"
  "Nationalismus (Philosophie)"
  "Pazifismus (Philosophie)"
  "Tierrechte (Philosophie)"
  "Tugenden (Philosophie)"
  "Laster (Philosophie)"
  "Sinn des Lebens (Philosophie)"
  "Determinismus (Philosophie)"
  "Freier Wille (Philosophie)"
  "Gott (Theologie)"
  "Seele (Philosophie)"
  "Geist (Philosophie)"
  "Bewusstsein (Philosophie)"
  "Unterbewusstsein (Psychologie)"
  "Archetyp (Psychologie)"
  "Kollektives Unbewusstes (Psychologie)"
  "Schatten (Psychologie)"
  "Persona (Psychologie)"
  "Selbst (Psychologie)"
  "Individuation (Psychologie)"
  "Synchronizität (Psychologie)"
  "Extroversion (Psychologie)"
  "Introversion (Psychologie)"
  "Neurotizismus (Psychologie)"
  "Offenheit (Psychologie)"
  "Gewissenhaftigkeit (Psychologie)"
  "Verträglichkeit (Psychologie)"
  "Extraversion (Psychologie)"
  "Big Five (Psychologie)"
  "Temperament (Psychologie)"
  "Charakter (Psychologie)"
  "Persönlichkeit (Psychologie)"
  "Identität (Psychologie)"
  "Selbstwertgefühl (Psychologie)"
  "Selbstvertrauen (Psychologie)"
  "Selbstkritik (Psychologie)"
  "Selbstreflexion (Psychologie)"
  "Achtsamkeit (Psychologie)"
  "Atemübungen (Praxis)"
  "Entspannung (Zustand)"
  "Stressmanagement (Praxis)"
  "Work-Life-Balance (Konzept)"
  "Zeitmanagement (Praxis)"
  "Prioritäten (Planung)"
  "Ziele (Planung)"
  "Erfolg (Konzept)"
  "Misserfolg (Konzept)"
  "Herausforderung (Konzept)"
  "Belohnung (Psychologie)"
  "Bestrafung (Psychologie)"
  "Lob (Kommunikation)"
  "Kritik (Kommunikation)"
  "Konflikt (Soziales)"
  "Kompromiss (Soziales)"
  "Kooperation (Soziales)"
  "Wettbewerb (Soziales)"
  "Führung (Management)"
  "Teamwork (Arbeit)"
  "Feedback (Kommunikation)"
  "aktives Zuhören (Kommunikation)"
  "Körpersprache (Kommunikation)"
  "Nonverbale Kommunikation (Kommunikation)"
  "Inklusion (Konzept)"
  "Diskriminierung (Soziales)"
  "Vorurteile (Soziales)"
  "Stereotypen (Soziales)"
  "Rassismus (Soziales)"
  "Sexismus (Soziales)"
  "Homophobie (Soziales)"
  "Transphobie (Soziales)"
  "Ableismus (Soziales)"
  "Antisemitismus (Soziales)"
  "Islamophobie (Soziales)"
  "Klassismus (Soziales)"
  "Agismus (Soziales)"
  "Mobbing (Soziales)"
  "Häusliche Gewalt (Soziales)"
  "Kindesmissbrauch (Soziales)"
  "Altenpflege (Soziales)"
  "Jugendhilfe (Soziales)"
  "Obdachlosigkeit (Soziales)"
  "Einkommensungleichheit (Soziales)"
  "Sozialstaat (Politik)"
  "Soziale Sicherung (Politik)"
  "Arbeitslosengeld (Wirtschaft)"
  "Krankenversicherung (Wirtschaft)"
  "Pflegeversicherung (Wirtschaft)"
  "Arbeitsrecht (Recht)"
  "Tarifvertrag (Wirtschaft)"
  "Gewerkschaften (Organisation)"
  "Arbeitgeberverbände (Organisation)"
  "Streik (Arbeitskampf)"
  "Lockout (Arbeitskampf)"
  "Mindestlohn (Wirtschaft)"
  "Arbeitszeit (Arbeit)"
  "Kündigungsschutz (Recht)"
  "Betriebsrat (Arbeit)"
  "Gleichstellung (Soziales)"
  "Frauenrechte (Soziales)"
  "Gleichberechtigung (Soziales)"
  "Gender Studies (Wissenschaft)"
  "Feminismus (Bewegung)"
  "Queer-Theorie (Wissenschaft)"
  "LGBTQ+ (Gemeinschaft)"
  "Sexuelle Orientierung (Identität)"
  "Geschlechtsidentität (Identität)"
  "Diversität (Konzept)"
  "Barrierefreiheit (Architektur)"
  "Inklusive Bildung (Bildung)"
  "Sonderpädagogik (Bildung)"
  "Interkulturelle Kommunikation (Kommunikation)"
  "Multikulturalismus (Gesellschaft)"
  "Assimilation (Soziales)"
  "Segregation (Soziales)"
  "Ghetto (Soziales)"
  "Flucht (Soziales)"
  "Asyl (Recht)"
  "Flüchtlingslager (Ort)"
  "Internationale Beziehungen (Politik)"
  "Außenpolitik (Politik)"
  "Internationale Organisationen (Politik)"
  "Weltsicherheitsrat (UN)"
  "Generalversammlung (UN)"
  "Internationaler Gerichtshof (Recht)"
  "Internationaler Strafgerichtshof (Recht)"
  "Afrikanische Union (Organisation)"
  "ASEAN (Organisation)"
  "G7 (Wirtschaft)"
  "G20 (Wirtschaft)"
  "OECD (Wirtschaft)"
  "Weltbank (Wirtschaft)"
  "Internationaler Währungsfonds (Wirtschaft)"
  "Welthandelsorganisation (Wirtschaft)"
  "Protektionismus (Wirtschaft)"
  "Zölle (Wirtschaft)"
  "Subventionen (Wirtschaft)"
  "Handelsabkommen (Wirtschaft)"
  "Binnenmarkt (Wirtschaft)"
  "Global Value Chains (Wirtschaft)"
  "Lieferketten (Wirtschaft)"
  "Nachhaltige Entwicklung (Wirtschaft)"
  "Klimagerechtigkeit (Umwelt)"
  "E-Mobilität (Technologie)"
  "Ozeanversauerung (Umwelt)"
  "Abholzung (Umwelt)"
  "Desertifikation (Umwelt)"
  "Bodenerosion (Umwelt)"
  "Wasserknappheit (Umwelt)"
  "Feinstaub (Umwelt)"
  "Stickoxide (Umwelt)"
  "Ozon (Umwelt)"
  "Smog (Umwelt)"
  "Treibhausgase (Umwelt)"
  "Kohlenstoffdioxid (Chemie)"
  "Methan (Chemie)"
  "Lachgas (Chemie)"
  "Klimamodelle (Wissenschaft)"
  "Temperaturanstieg (Klima)"
  "Extremwetterereignisse (Klima)"
  "Überschwemmungen (Naturkatastrophe)"
  "Dürren (Naturkatastrophe)"
  "Waldbrände (Naturkatastrophe)"
  "Eiskappen (Geografie)"
  "Polareis (Geografie)"
  "Meeresströmungen (Ozeanographie)"
  "Golfstrom (Ozeanographie)"
  "El Niño (Klima)"
  "La Niña (Klima)"
  "Zyklone (Meteorologie)"
  "Gezeiten (Astronomie)"
  "Ebbe (Gezeiten)"
  "Flut (Gezeiten)"
  "Nebel (Astronomie)"
  "Quasare (Astronomie)"
  "Pulsare (Astronomie)"
  "Neutronensterne (Astronomie)"
  "Weiße Zwerge (Astronomie)"
  "Rote Riesen (Astronomie)"
  "Urknall (Kosmologie)"
  "Expansion des Universums (Kosmologie)"
  "Dunkle Materie (Kosmologie)"
  "Dunkle Energie (Kosmologie)"
  "Lichtjahr (Astronomie)"
  "Parsec (Astronomie)"
  "Kosmische Strahlung (Physik)"
  "Sonnenwinde (Physik)"
  "Polarlichter (Phänomen)"
  "Raumstation (Technologie)"
  "Marsrover (Technologie)"
  "Raumsonde (Technologie)"
  "Radioteleskop (Technologie)"
  "Hubble-Teleskop (Technologie)"
  "James-Webb-Teleskop (Technologie)"
  "Kosmonaut (Beruf)"
  "ISS (Raumfahrt)"
  "NASA (Organisation)"
  "ESA (Organisation)"
  "Roskosmos (Organisation)"
  "JAXA (Organisation)"
  "CSA (Organisation)"
  "SpaceX (Unternehmen)"
  "Blue Origin (Unternehmen)"
  "Virgin Galactic (Unternehmen)"
  "Proton (Physik)"
  "Neutron (Physik)"
  "Elektron (Physik)"
  "Photon (Physik)"
  "Quark (Physik)"
  "Lepton (Physik)"
  "Hadron (Physik)"
  "Boson (Physik)"
  "Fermion (Physik)"
  "Standardmodell (Physik)"
  "Higgs-Boson (Physik)"
  "Kernfusion (Physik)"
  "Kernspaltung (Physik)"
  "Kernkraftwerk (Technologie)"
  "Radioaktivität (Physik)"
  "Isotope (Chemie)"
  "Verbindungen (Chemie)"
  "Chemische Reaktionen (Chemie)"
  "Säure-Base-Reaktion (Chemie)"
  "Redoxreaktion (Chemie)"
  "Organische Chemie (Chemie)"
  "Anorganische Chemie (Chemie)"
  "Biochemie (Chemie)"
  "Polymer (Chemie)"
  "Kunststoffe (Material)"
  "Metalle (Material)"
  "Legierungen (Material)"
  "Beton (Material)"
  "Stoffe (Material)"
  "Farben (Material)"
  "Pigmente (Material)"
  "Farbspektrum (Physik)"
  "Ultraviolett (Physik)"
  "Infrarot (Physik)"
  "Röntgenstrahlen (Physik)"
  "Gammastrahlen (Physik)"
  "Strahlung (Physik)"
  "Wellen (Physik)"
  "Frequenzen (Physik)"
  "Amplituden (Physik)"
  "Resonanz (Physik)"
  "Ultraschall (Physik)"
  "Infraschall (Physik)"
  "Töne (Musik)"
  "Noten (Musik)"
  "Akkorde (Musik)"
  "Melodie (Musik)"
  "Rhythmus (Musik)"
  "Harmonie (Musik)"
  "Komposition (Musik)"
  "Choreographie (Kunst)"
  "Folkloretanz (Kunst)"
  "Leichtathletik (Sport)"
  "Springen (Sport)"
  "Werfen (Sport)"
  "Turnen (Sport)"
  "Kraftsport (Sport)"
  "Ausdauersport (Sport)"
  "Kampfsport (Sport)"
  "Mannschaftssport (Sport)"
  "Individualsport (Sport)"
  "Paralympics (Sport)"
  "Volleyball (Sport)"
  "Handball (Sport)"
  "Eishockey (Sport)"
  "Golf (Sport)"
  "Reiten (Sport)"
  "Fahrradfahren (Sport)"
  "Kanufahren (Sport)"
  "Rudern (Sport)"
  "Angeln (Hobby)"
  "Jagen (Hobby)"
  "Briefmarken (Sammeln)"
  "Antiquitäten (Sammeln)"
  "Basteln (Hobby)"
  "Malen (Hobby)"
  "Zeichnen (Hobby)"
  "Stricken (Hobby)"
  "Nähen (Hobby)"
  "Gärtnern (Hobby)"
  "Kochen (Hobby)"
  "Backen (Hobby)"
  "Fotografieren (Hobby)"
  "Camping (Hobby)"
  "Wohnmobil (Fahrzeug)"
  "Zelt (Ausrüstung)"
  "Schlafsack (Ausrüstung)"
  "Rucksack (Ausrüstung)"
  "Wanderwege (Wandern)"
  "Campingplatz (Reisen)"
  "Ferienwohnung (Reisen)"
  "Hotel (Reisen)"
  "Jugendherberge (Reisen)"
  "Motel (Reisen)"
  "Gästehaus (Reisen)"
  "Motorrad (Transport)"
  "Kreuzfahrtschiff (Transport)"
  "Fähre (Transport)"
  "Mietwagen (Transport)"
  "Reisebüro (Dienstleistung)"
  "Landkarte (Geografie)"
  "Kompass (Ausrüstung)"
  "GPS-Gerät (Technologie)"
  "Navigation (Technologie)"
  "Flughafen (Infrastruktur)"
  "Bahnhof (Infrastruktur)"
  "Busbahnhof (Infrastruktur)"
  "Hafen (Infrastruktur)"
  "Autobahn (Infrastruktur)"
  "Bundesstraße (Infrastruktur)"
  "Landstraße (Infrastruktur)"
  "Hauptstadt (Stadt)"
  "Großstadt (Stadt)"
  "Kleinstadt (Stadt)"
  "Vorort (Stadt)"
  "Industriegebiet (Wirtschaft)"
  "Wohngebiet (Stadt)"
  "Gewerbegebiet (Wirtschaft)"
  "Einkaufszentrum (Handel)"
  "Markt (Handel)"
  "Supermarkt (Handel)"
  "Restaurant (Gastronomie)"
  "Café (Gastronomie)"
  "Bar (Gastronomie)"
  "Diskothek (Freizeit)"
  "Konzerthalle (Freizeit)"
  "Bibliothek (Bildung)"
  "Forschungsinstitut (Wissenschaft)"
  "Arztpraxis (Gesundheit)"
  "Apotheke (Gesundheit)"
  "Polizeistation (Sicherheit)"
  "Feuerwehrwache (Sicherheit)"
  "Bäckerei (Handwerk)"
  "Metzgerei (Handwerk)"
  "Schuhmacher (Handwerk)"
  "Schmied (Handwerk)"
  "Tischler (Handwerk)"
  "Installateur (Handwerk)"
  "Elektriker (Handwerk)"
  "Maurer (Handwerk)"
  "Dachdecker (Handwerk)"
  "Zimmermann (Handwerk)"
  "Gärtner (Beruf)"
  "Bauer (Beruf)"
  "Fischer (Beruf)"
  "Jäger (Beruf)"
  "Beruf (Arbeit)"
  "Arbeit (Tätigkeit)"
  "Gehalt (Wirtschaft)"
  "Lohn (Wirtschaft)"
  "Pension (Sozialversicherung)"
  "Berufsausbildung (Bildung)"
  "Weiterbildung (Bildung)"
  "Berufsberatung (Dienstleistung)"
  "Arbeitsamt (Behörde)"
  "Jobsuche (Arbeit)"
  "Bewerbung (Arbeit)"
  "Vorstellungsgespräch (Arbeit)"
  "Lebenslauf (Bewerbung)"
  "Zeugnisse (Dokument)"
  "Praktikum (Arbeit)"
  "Nebenjob (Arbeit)"
  "Freiberufler (Arbeit)"
  "Selbstständigkeit (Arbeit)"
  "Start-up (Unternehmen)"
  "Unternehmen (Wirtschaft)"
  "Konzerne (Wirtschaft)"
  "KMU (Wirtschaft)"
  "Genossenschaft (Wirtschaft)"
  "Verein (Organisation)"
  "Non-Profit-Organisation (Organisation)"
  "NGO (Organisation)"
  "Berufsverband (Organisation)"
  "Public Relations (Kommunikation)"
  "Marketing (Wirtschaft)"
  "Werbung (Wirtschaft)"
  "Verkauf (Wirtschaft)"
  "Einkauf (Wirtschaft)"
  "Supply Chain Management (Wirtschaft)"
  "Qualitätsmanagement (Wirtschaft)"
  "Risikomanagement (Wirtschaft)"
  "Nachhaltigkeitsmanagement (Wirtschaft)"
  "CSR (Wirtschaft)"
  "Shareholder Value (Wirtschaft)"
  "Stakeholder (Wirtschaft)"
  "Führungskraft (Beruf)"
  "Mitarbeiter (Beruf)"
  "Team (Organisation)"
  "Abteilung (Organisation)"
  "Hierarchie (Organisation)"
  "Flache Hierarchien (Organisation)"
  "Co-Working (Arbeitsform)"
  "Maschinelles Lernen (KI)"
  "Deep Learning (KI)"
  "Neuronale Netze (KI)"
  "Internet der Dinge (IoT)"
  "Kryptowährungen (Finanzen)"
  "Smart Contracts (Blockchain)"
  "Mixed Reality (Technologie)"
  "Hacking (IT)"
  "Malware (IT)"
  "Phishing (IT)"
  "Spam (IT)"
  "Firewall (IT)"
  "Verschlüsselung (IT)"
  "Passwort (IT)"
  "Fingerabdruck (Biometrie)"
  "Gesichtserkennung (Biometrie)"
  "Iris-Scan (Biometrie)"
  "Bilderkennung (Technologie)"
  "Mustererkennung (Technologie)"
  "Sprachverarbeitung (KI)"
  "Bildverarbeitung (KI)"
  "Humanoide Roboter (Robotik)"
  "Drohnen (Technologie)"
  "Autonomes Fahren (Technologie)"
  "Selbstfahrende Autos (Technologie)"
  "Flugtaxis (Technologie)"
  "Hyperloop (Technologie)"
  "Magnetbahn (Technologie)"
  "Superschallflugzeug (Technologie)"
  "Weltraumschrott (Astronomie)"
  "GLONASS (Technologie)"
  "Galileo (Technologie)"
  "Beidou (Technologie)"
  "Starlink (Technologie)"
  "Teleskop (Optik)"
  "Mikroskop (Optik)"
  "Laser (Technologie)"
  "Faseroptik (Technologie)"
  "Quantencomputer (Technologie)"
  "Supraleiter (Physik)"
  "Nanomaterialien (Materialwissenschaft)"
  "Graphen (Materialwissenschaft)"
  "Kohlenstoffnanoröhren (Materialwissenschaft)"
  "Smart Materials (Materialwissenschaft)"
  "Selbstheilende Materialien (Materialwissenschaft)"
  "CRISPR-Cas9 (Biotechnologie)"
  "Künstliche Organe (Medizin)"
  "3D-Druck (Technologie)"
  "Bio-Druck (Technologie)"
  "Exoskelette (Technologie)"
  "Prothesen (Medizin)"
  "Implantate (Medizin)"
  "Smartwatch (Technologie)"
  "Fitness-Tracker (Technologie)"
  "Carsharing (Mobilität)"
  "E-Scooter (Mobilität)"
  "Fahrradleasing (Mobilität)"
  "Öffentlicher Nahverkehr (Mobilität)"
  "Schiene (Transport)"
  "Straße (Transport)"
  "Wasserweg (Transport)"
  "Luftweg (Transport)"
  "Supply Chain (Wirtschaft)"
  "Warenlager (Logistik)"
  "Transportmittel (Logistik)"
  "Last-Mile-Delivery (Logistik)"
  "Jahreszeiten (Wetter)"
  "Sonnenschein (Wetter)"
  "Vulkanausbruch (Naturkatastrophe)"
  "Lawine (Naturkatastrophe)"
  "Erdrutsch (Naturkatastrophe)"
  "Eisschmelze (Klima)"
  "Korallenbleiche (Umwelt)"
  "Wasserverschmutzung (Umwelt)"
  "Bodenverschmutzung (Umwelt)"
  "Lärmbelästigung (Umwelt)"
  "Lichtverschmutzung (Umwelt)"
  "Naturschutzgebiete (Umwelt)"
  "Nationalparks (Umwelt)"
  "Wälder (Natur)"
  "Gebirge (Natur)"
  "Wüsten (Natur)"
  "Flüsse (Natur)"
  "Seen (Natur)"
  "Inseln (Natur)"
  "Küsten (Natur)"
  "Strände (Natur)"
  "Klippen (Natur)"
  "Geysire (Natur)"
  "Wasserfälle (Natur)"
  "Fjorde (Natur)"
  "Wüstenlandschaften (Natur)"
  "Steppen (Natur)"
  "Savannen (Natur)"
  "Tundra (Natur)"
  "Taiga (Natur)"
  "Mangroven (Natur)"
  "Sümpfe (Natur)"
  "Moore (Natur)"
  "Feuchtgebiete (Natur)"
  "Auen (Natur)"
  "Wiesen (Natur)"
  "Felder (Natur)"
  "Gärten (Natur)"
  "Parks (Natur)"
  "Zoologische Gärten (Tierhaltung)"
  "Botanische Gärten (Pflanzen)"
  "Tierheime (Tierhaltung)"
  "Tierschutz (Tierhaltung)"
  "Artenschutz (Tierhaltung)"
  "Wilderei (Kriminalität)"
  "Tierversuche (Wissenschaft)"
  "Massentierhaltung (Landwirtschaft)"
  "Fleischkonsum (Ernährung)"
  "Pflanzenbasierte Ernährung (Ernährung)"
  "Biologische Landwirtschaft (Landwirtschaft)"
  "Permakultur (Landwirtschaft)"
  "Hydroponik (Landwirtschaft)"
  "Aeroponik (Landwirtschaft)"
  "Vertikale Landwirtschaft (Landwirtschaft)"
  "Urbane Landwirtschaft (Landwirtschaft)"
  "Nachhaltige Landwirtschaft (Landwirtschaft)"
  "Agroforstwirtschaft (Landwirtschaft)"
  "Gräser (Biologie)"
  "Farne (Biologie)"
  "Moose (Biologie)"
  "Flechten (Biologie)"
  "Protozoen (Biologie)"
  "Einzeller (Biologie)"
  "Mehrzeller (Biologie)"
  "Gene (Biologie)"
  "Photosynthese (Biologie)"
  "Epigenetik (Biologie)"
  "Neurobiologie (Biologie)"
  "Kognitionswissenschaft (Wissenschaft)"
  "Soziologie (Wissenschaft)"
  "Anthropologie (Wissenschaft)"
  "Archäologie (Wissenschaft)"
  "Theologie (Wissenschaft)"
  "Linguistik (Wissenschaft)"
  "Geowissenschaften (Wissenschaft)"
  "Informatik (Wissenschaft)"
  "Ingenieurwesen (Wissenschaft)"
  "Rechtswissenschaft (Wissenschaft)"
  "Wirtschaftswissenschaft (Wissenschaft)"
  "Politikwissenschaft (Wissenschaft)"
  "Kommunikationswissenschaft (Wissenschaft)"
  "Medienwissenschaft (Wissenschaft)"
  "Kulturwissenschaft (Wissenschaft)"
  "Kunstwissenschaft (Wissenschaft)"
  "Musikwissenschaft (Wissenschaft)"
  "Sportwissenschaft (Wissenschaft)"
  "Erziehungswissenschaft (Wissenschaft)"
  "Kriminologie (Wissenschaft)"
  "Forensik (Wissenschaft)"
  "Umweltwissenschaft (Wissenschaft)"
  "Nanowissenschaft (Wissenschaft)"
  "Blockchain-Technologie (Wissenschaft)"
  "Quantencomputing (Wissenschaft)"
  "CRISPR (Biotechnologie)"
  "Synthetische Biologie (Biotechnologie)"
  "Bioinformatik (Biotechnologie)"
  "Neuroprothetik (Medizin)"
  "Roboterchirurgie (Medizin)"
  "Telemedizin (Medizin)"
  "Stammzelltherapie (Medizin)"
  "Immuntherapie (Medizin)"
  "Krebstherapie (Medizin)"
  "Diabetesmanagement (Medizin)"
  "Herztransplantation (Medizin)"
  "Organspende (Medizin)"
  "Bluttransfusion (Medizin)"
  "Impfstoffentwicklung (Medizin)"
  "Pandemieprävention (Medizin)"
  "Epidemiologie (Medizin)"
  "Virologie (Medizin)"
  "Bakteriologie (Medizin)"
  "Toxikologie (Medizin)"
  "Pathologie (Medizin)"
  "Anatomie (Medizin)"
  "Physiologie (Medizin)"
  "Histologie (Medizin)"
  "Zytologie (Medizin)"
  "Molekularbiologie (Medizin)"
  "Zellbiologie (Medizin)"
  "Mikrobiologie (Medizin)"
  "Parasitologie (Medizin)"
  "Infektionskrankheiten (Medizin)"
  "Chronische Krankheiten (Medizin)"
  "Seltene Krankheiten (Medizin)"
  "Psychiatrie (Medizin)"
  "Neurologie (Medizin)"
  "Neurochirurgie (Medizin)"
  "Orthopädie (Medizin)"
  "Kardiologie (Medizin)"
  "Pulmologie (Medizin)"
  "Gastroenterologie (Medizin)"
  "Nephrologie (Medizin)"
  "Endokrinologie (Medizin)"
  "Dermatologie (Medizin)"
  "Ophthalmologie (Medizin)"
  "HNO (Medizin)"
  "Urologie (Medizin)"
  "Gynäkologie (Medizin)"
  "Pädiatrie (Medizin)"
  "Anästhesiologie (Medizin)"
  "Radiologie (Medizin)"
  "Onkologie (Medizin)"
  "Hämatologie (Medizin)"
  "Rheumatologie (Medizin)"
  "Sportmedizin (Medizin)"
  "Ernährungsmedizin (Medizin)"
  "Alternativmedizin (Medizin)"
  "Homöopathie (Medizin)"
  "Akupunktur (Medizin)"
  "Osteopathie (Medizin)"
  "Chiropraktik (Medizin)"
  "Phytotherapie (Medizin)"
  "Aromatherapie (Medizin)"
  "Entspannungstechniken (Medizin)"
  "Bewegungstherapie (Medizin)"
  "Physiotherapie (Medizin)"
  "Ergotherapie (Medizin)"
  "Logopädie (Medizin)"
  "Sozialpädiatrie (Medizin)"
  "Palliativmedizin (Medizin)"
  "Hospiz (Medizin)"
  "Sterbebegleitung (Medizin)"
  "Ethik in der Medizin (Medizin)"
  "Patientenrechte (Medizin)"
  "Ärztekammer (Organisation)"
  "Krankenkassen (Organisation)"
  "Gesundheitswesen (System)"
  "Public Health (Gesundheit)"
  "Epidemien (Gesundheit)"
  "Pandemien (Gesundheit)"
  "Impfprogramme (Gesundheit)"
  "Hygiene (Gesundheit)"
  "Sanitation (Gesundheit)"
  "Trinkwasser (Ressource)"
  "Abwasser (Ressource)"
  "Abfallentsorgung (Umwelt)"
  "Luftqualität (Umwelt)"
  "Lärmschutz (Umwelt)"
  "Strahlenschutz (Umwelt)"
  "Lebensmittelsicherheit (Ernährung)"
  "Arbeitssicherheit (Arbeit)"
  "Unfallverhütung (Arbeit)"
  "Zivilschutz (Sicherheit)"
  "Rettungsdienst (Sicherheit)"
  "Friedenserhaltung (Politik)"
  "Abrüstung (Politik)"
  "Geopolitik (Politik)"
  "Supermächte (Politik)"
  "Schwellenländer (Wirtschaft)"
  "Globaler Süden (Geografie)"
  "Globaler Norden (Geografie)"
  "Nord-Süd-Konflikt (Politik)"
  "Ost-West-Konflikt (Politik)"
  "Lokalisierung (Wirtschaft)"
  "Dezentralisierung (Politik)"
  "Zentralisierung (Politik)"
  "Subsidiarität (Politik)"
  "Einheitsstaat (Politik)"
  "Autoritarismus (Staatsform)"
  "Totalitarismus (Staatsform)"
  "Aristokratie (Staatsform)"
  "Plutokratie (Staatsform)"
  "Ochlokratie (Staatsform)"
  "Timokratie (Staatsform)"
  "Meritokratie (Staatsform)"
  "Technokratie (Staatsform)"
  "Bürokratie (Verwaltung)"
  "Verwaltung (Organisation)"
  "Rechtsstaat (Recht)"
  "Gewaltenteilung (Recht)"
  "Rechtsstaatlichkeit (Recht)"
  "Wahlrecht (Recht)"
  "Freiheit der Meinungsäußerung (Recht)"
  "Versammlungsfreiheit (Recht)"
  "Religionsfreiheit (Recht)"
  "Recht auf Bildung (Recht)"
  "Recht auf Gesundheit (Recht)"
  "Recht auf Arbeit (Recht)"
  "Recht auf Wohnen (Recht)"
  "Recht auf soziale Sicherheit (Recht)"
  "Wohlfahrtsstaat (Politik)"
  "Steuersystem (Wirtschaft)"
  "Einkommensteuer (Wirtschaft)"
  "Umsatzsteuer (Wirtschaft)"
  "Mehrwertsteuer (Wirtschaft)"
  "Erbschaftsteuer (Wirtschaft)"
  "Grundsteuer (Wirtschaft)"
  "Haushalt (Wirtschaft)"
  "Staatsschulden (Wirtschaft)"
  "Staatsdefizit (Wirtschaft)"
  "Staatsüberschuss (Wirtschaft)"
  "Konjunktur (Wirtschaft)"
  "Depression (Wirtschaft)"
  "Boom (Wirtschaft)"
  "Stagflation (Wirtschaft)"
  "Erwerbstätigkeit (Wirtschaft)"
  "Beschäftigung (Wirtschaft)"
  "Produktivität (Wirtschaft)"
  "Gini-Koeffizient (Wirtschaft)"
  "Einkommensverteilung (Wirtschaft)"
  "Vermögensverteilung (Wirtschaft)"
  "Mittelschicht (Soziales)"
  "Soziale Mobilität (Soziales)"
  "Generationengerechtigkeit (Soziales)"
  "Umweltgerechtigkeit (Soziales)"
  "Gendergerechtigkeit (Soziales)"
  "Rassengerechtigkeit (Soziales)"
  "Gleichbehandlung (Soziales)"
  "Anti-Diskriminierung (Soziales)"
  "Sitten (Kultur)"
  "Dialekt (Kultur)"
  "Akzent (Kultur)"
  "Küche (Kultur)"
  "Nationalismus (Kultur)"
  "Patriotismus (Kultur)"
  "Kulturerbe (Kultur)"
  "UNESCO-Weltkulturerbe (Kultur)"
  "Archive (Kultur)"
  "Ausgrabungen (Archäologie)"
  "Fossilien (Archäologie)"
  "Artefakte (Archäologie)"
  "Moderne (Geschichte)"
  "Renaissance (Geschichte)"
  "Barock (Geschichte)"
  "Rokoko (Geschichte)"
  "Klassizismus (Geschichte)"
  "Realismus (Geschichte)"
  "Impressionismus (Geschichte)"
  "Expressionismus (Geschichte)"
  "Kubismus (Geschichte)"
  "Surrealismus (Geschichte)"
  "Pop Art (Geschichte)"
  "Abstrakter Expressionismus (Kunst)"
  "Postmoderne (Kunst)"
  "Zeitgenössische Kunst (Kunst)"
  "Performance-Kunst (Kunst)"
  "Installationskunst (Kunst)"
  "Street Art (Kunst)"
  "Graffiti (Kunst)"
  "Tätowierungen (Kultur)"
  "Piercings (Kultur)"
  "Stile (Mode)"
  "Designer (Mode)"
  "Marken (Mode)"
  "Goldschmied (Handwerk)"
  "Kosmetik (Produkte)"
  "Parfüm (Produkte)"
  "Einrichtung (Wohnen)"
  "Möbel (Wohnen)"
  "Dekoration (Wohnen)"
  "Licht (Wohnen)"
  "Farben (Wohnen)"
  "Materialien (Wohnen)"
  "Innenarchitektur (Wohnen)"
  "Landschaftsarchitektur (Wohnen)"
  "Gemüse (Garten)"
  "Obst (Garten)"
  "Kräuter (Garten)"
  "Schädlinge (Garten)"
  "Dünger (Garten)"
  "Boden (Garten)"
  "Bewässerung (Garten)"
  "Gartenwerkzeuge (Garten)"
  "Rasen (Garten)"
  "Hecken (Garten)"
  "Teiche (Garten)"
  "Brunnen (Garten)"
  "Skulpturen (Garten)"
  "Wege (Garten)"
  "Zäune (Garten)"
  "Mauern (Garten)"
  "Terrasse (Wohnen)"
  "Balkon (Wohnen)"
  "Wintergarten (Wohnen)"
  "Keller (Wohnen)"
  "Dachboden (Wohnen)"
  "Garage (Wohnen)"
  "Carport (Wohnen)"
  "Einfahrt (Wohnen)"
  "Vorgarten (Wohnen)"
  "Hinterhof (Wohnen)"
  "Gartenhaus (Wohnen)"
  "Geräteschuppen (Wohnen)"
  "Gewächshaus (Garten)"
  "Hochbeet (Garten)"
  "Komposthaufen (Garten)"
  "Regentonne (Garten)"
  "Solaranlage (Energie)"
  "Wärmepumpe (Energie)"
  "Photovoltaikanlage (Energie)"
  "Regenwassernutzung (Umwelt)"
  "Smart Home Systeme (Technologie)"
  "Alarmanlage (Sicherheit)"
  "Überwachungskamera (Sicherheit)"
  "Rauchmelder (Sicherheit)"
  "Kohlenmonoxidmelder (Sicherheit)"
  "Brandbekämpfung (Sicherheit)"
  "Feuerlöscher (Sicherheit)"
  "Erste Hilfe (Medizin)"
  "Notfall (Situation)"
  "Unfall (Situation)"
  "Verletzung (Medizin)"
  "Stressabbau (Psychologie)"
  "Atemtechniken (Praxis)"
  "Schlafhygiene (Gesundheit)"
  "Traumdeutung (Psychologie)"
  "Luzides Träumen (Psychologie)"
  "Gedächtnistraining (Psychologie)"
  "Konzentrationsübungen (Psychologie)"
  "Kognitive Fähigkeiten (Psychologie)"
  "Problemlösungskompetenz (Psychologie)"
  "Erfindung (Wissenschaft)"
  "Entdeckung (Wissenschaft)"
  "Forschungsmethoden (Wissenschaft)"
  "Experiment (Wissenschaft)"
  "Hypothese (Wissenschaft)"
  "Theorie (Wissenschaft)"
  "Gesetz (Wissenschaft)"
  "Modell (Wissenschaft)"
  "Simulation (Wissenschaft)"
  "Datenanalyse (Wissenschaft)"
  "Vernetzung (Technologie)"
  "Esports (Sport)"
)

# Schleife durch das Array und sende für jedes Thema eine POST-Anfrage
for thema in "${themen[@]}"; do
  # Erstelle den Daten-String
  data="${thema}"

  # Führe den cURL-Befehl aus
  echo "Sende Thema: $data"
  curl -X POST http://localhost:8080/themen \
  -H "Content-Type: text/plain" \
  -d "$data"

  # Füge eine neue Zeile für die Lesbarkeit der Ausgabe hinzu
  echo ""
done

echo "Alle Themen wurden gesendet."

